name: Android Build (Option B)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    # 1️⃣ Checkout source code
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2️⃣ Setup Java
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: gradle

    # 3️⃣ Install system Gradle
    - name: Install Gradle
      run: |
        sudo apt-get update
        sudo apt-get install -y gradle
        gradle -v

    # 4️⃣ Cache Gradle dependencies
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: gradle-cache-

    # 5️⃣ Build APK
    - name: Build Debug APK
      run: gradle assembleDebug

    # 6️⃣ Upload APK
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk