name: Chess Engine Server

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  run-chess-engine:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y stockfish
    
    - name: Install Python dependencies
      run: |
        pip install flask python-chess stockfish pyngrok
    
    - name: Run chess engine server
      env:
        NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
      run: |
        python chess_engine.py
